---
# ansible install playbook for docker-zeek.
# Version: 202408061413
# sample runs:
# 	Run this, with a comma separated list of hostnames from the above file with a comma at the end of the list:
#
# 	ansible-playbook -C -K -i "ro810,ub2404," -e "install_hosts=ro810,ub2404," ~/.ansible/playbooks/install_zeek.yml | grep -v '^skipping: '	#-C (no changes) means do a dry run
# 	ansible-playbook -K -i "ro810,ub2404," -e "install_hosts=ro810,ub2404," ~/.ansible/playbooks/install_zeek.yml | grep -v '^skipping: '

# Many thanks to but-i-am-dominator for his help with this playbook.


- name: "Zeek Install: Zeek installer."
  hosts: "{{  install_hosts  }}"
  become: true

  vars:
    zeek_version: "REPLACE_ME"								
    zeek_container_image: "activecm/zeek:{{  zeek_version }}"
    clickhouse_container_image: clickhouse/clickhouse-server:latest
    ansible_python_interpreter: /bin/python3							# Centos 7 defaults to using python2, so we force python 3.  This change does not break any other distros

#The install_pre.yml script should already have been run by this point

  tasks:
#Make directories
    - name: "Zeek Install: Create zeek directories."
      ansible.builtin.file:
        path: "{{  item  }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /opt/zeek/
        - /opt/zeek/etc/
        - /opt/zeek/logs/
        - /opt/zeek/logs/stats/
        - /opt/zeek/manual-logs/
        - /opt/zeek/share/
        - /opt/zeek/share/zeek/
        - /opt/zeek/share/zeek/site/
        - /opt/zeek/share/zeek/site/autoload/
        - /opt/zeek/spool/
        - /opt/zeek/spool/installed-scripts-do-not-touch/
        - /opt/zeek/spool/manager/
        - /opt/zeek/spool/proxy-1/
        - /opt/zeek/spool/tmp/
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

#Install Zeek
    #Following pulls right from dockerhub.  We may not be able to do this if the system is airgapped
    #- name: "Zeek Install: Install {{  zeek_container_image  }} docker image."
    #  block:
    - name: "Pull from dockerhub container repo"
      community.docker.docker_image:
        name: "{{  zeek_container_image  }}"
        source: pull
        force_source: true
    #  rescue:
    #    - name: "Zeek Install: Transfer Zeek container image to target system"
    #      copy:
    #        src: "zeek-{{  zeek_version  }}-image.tar"
    #        dest: /opt/zeek
    #        owner: root
    #        group: root
    #        mode: 0644
    #    - name: "Install Zeek container image from file"
    #      community.docker.docker_image_load:
    #        path: "/opt/zeek/zeek-{{  zeek_version  }}-image.tar"
    #      register: load_result
    #      #This final one prints a list of the loaded images if we use the above 2 stanzas to load from a file.
    #    - name: "Zeek Install: Print loaded image names."
    #      ansible.builtin.debug:
    #        msg: "Loaded the following images: {{  load_result.image_names | join(', ')  }}"
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

    - name: "Zeek Install: Transfer zeek shell script to target system."
      copy:
        src: ./opt/zeek
        dest: /usr/local/bin/zeek
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

    #- name: "Zeek Install: Transfer zeek install files to /opt/zeek."
    #  copy:
    #    src: ./opt/
    #    dest: /opt/zeek
    #    owner: root
    #    group: root
    #    mode: 0755
    #  tags:
    #    - docker
    #    - zeek
    #    - linux
    #    - linuxdeb
    #    - linuxrpm

    #- name: "Zeek Install: Transfer zeek user files to /opt/zeek/etc."
    #  copy:
    #    src: ./etc/
    #    dest: /opt/zeek/etc
    #    owner: root
    #    group: root
    #    mode: 0755
    #  tags:
    #    - docker
    #    - zeek
    #    - linux
    #    - linuxdeb
    #    - linuxrpm


#The install_post.yml script should be run next
