# ansible install playbook for rita

- name: "RITA Install: RITA installer."
  hosts: "{{ install_hosts }}"
  become: true

  vars:
    rita_version: "REPLACE_ME"
    rita_container_image: "ghcr.io/activecm/rita:{{ rita_version }}"
    clickhouse_container_image: clickhouse/clickhouse-server:latest
    ansible_python_interpreter: /bin/python3

  # the install_pre.yml script should already have been run by this point

  tasks:
    # make directories
    - name: "RITA Install: Create configuration directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/rita/
        - /opt/rita/
      tags:
        - docker
        - rita
        - linux
        - linuxdeb
        - linuxrpm

    # install RITA
    # the following pulls right from dockerhub. We may not be able to do this if the system is airgapped
    - name: "RITA Install: Install {{ rita_container_image }} docker image"
      block:
        - name: "Pull from Github.io Container repo"
          community.docker.docker_image:
            name: "{{ rita_container_image }}"
            source: pull
            force_source: true
      rescue:
        - name: "RITA Install: Transfer RITA container image to target system"
          copy:
            src: "rita-{{ rita_version }}-image.tar"
            dest: /opt/rita
            owner: root
            group: root
            mode: 0644
        - name: "Install {{ rita_container_name }} container image from file"
          community.docker.docker_image_load:
            path: "/opt/rita/rita-{{ rita_version }}-image.tar"
          register: load_result
          # this final one prints a list of the loaded images if we use the above 2 stanzas to load from a file
        - name: "RITA Install: Print loaded image names"
          ansible.builtin.debug:
            msg: "Loaded the following images: {{ load_result.image_names | join(', ') }}"
      tags:
        - docker
        - rita
        - linux
        - linuxdeb
        - linuxrpm

    - name: "RITA Install: Transfer rita shell script to target system"
      copy:
        src: ./opt/rita.sh
        dest: /usr/local/bin/rita
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - rita
        - linux
        - linuxdeb
        - linuxrpm

    - name: "RITA Install: Transfer rita install files to /opt/rita"
      copy:
        src: ./opt/
        dest: /opt/rita
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - rita
        - linux
        - linuxdeb
        - linuxrpm

    - name: "RITA Install: Transfer rita user files to /etc/rita"
      copy:
        src: ./etc/
        dest: /etc/rita
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - rita
        - linux
        - linuxdeb
        - linuxrpm
