# ansible install playbook for docker-zeek

- name: "Zeek Install: Zeek installer"
  hosts: "{{ install_hosts }}"
  become: true

  vars:
    zeek_version: "REPLACE_ME"
    zeek_container_image: "activecm/zeek:{{ zeek_version }}"
    clickhouse_container_image: clickhouse/clickhouse-server:latest
    ansible_python_interpreter: /bin/python3
    local_known_hosts: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

  # the install_pre.yml script should already have been run by this point

  tasks:
    # make directories
    - name: "Zeek Install: Create zeek directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /opt/zeek/
        - /opt/zeek/etc/
        - /opt/zeek/logs/
        - /opt/zeek/logs/stats/
        - /opt/zeek/manual-logs/
        - /opt/zeek/share/
        - /opt/zeek/share/zeek/
        - /opt/zeek/share/zeek/site/
        - /opt/zeek/share/zeek/site/autoload/
        - /opt/zeek/spool/
        - /opt/zeek/spool/installed-scripts-do-not-touch/
        - /opt/zeek/spool/manager/
        - /opt/zeek/spool/proxy-1/
        - /opt/zeek/spool/tmp/
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

    # install Zeek
    # the following pulls right from dockerhub. We may not be able to do this if the system is airgapped
    - name: "Pull from dockerhub container repo"
      community.docker.docker_image:
        name: "{{ zeek_container_image }}"
        source: pull
        force_source: true
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

    - name: "Zeek Install: Transfer zeek shell script to target system"
      copy:
        src: ./opt/zeek
        dest: /usr/local/bin/zeek
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - zeek
        - linux
        - linuxdeb
        - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Transfer zeek_log_transport.sh shell script to target system."
    #   copy:
    #     src: ./opt/zeek_log_transport.sh
    #     dest: /usr/local/bin/zeek_log_transport.sh
    #     owner: root
    #     group: root
    #     mode: 0755
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Transfer zeek_log_transport.cron to target system."
    #   copy:
    #     src: "{{ lookup('env', 'PWD') }}/zeek_log_transport.cron"
    #     dest: /etc/cron.d/zeek_log_transport
    #     owner: root
    #     group: root
    #     mode: 0644
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Place name of remote user in zeek_log_transport cron file"
    #   ansible.builtin.replace:
    #     path: /etc/cron.d/zeek_log_transport
    #     regexp: "^(.*)NON_ROOT_ACCOUNT_NAME(.*)$"
    #     replace: '\1{{ lookup("env", "USER") }}\2'
    #     mode: 0644
    #     owner: root
    #     group: root
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    - name: "Zeek Install: check whether node.cfg exists to decide if this is the first time running zeek"
      stat:
        path: /opt/zeek/etc/node.cfg
      register: node_stat

    # this cannot be run on the first install, as zeekcfg needs to be run first to let the user select their interface(s).
    # the user will need to run this by hand after the install completes.
    - name: "Zeek Install: Start Zeek"
      shell: "/usr/local/bin/zeek start"
      when: (node_stat.stat.exists == true)
      tags:
        - docker
        - hunt
        - linux
        - linuxdeb
        - linuxrpm

    # this cannot be run on the first install, as zeekcfg needs to be run first to let the user select their interface(s).
    # the user will need to run this by hand after the install completes.
    - name: "Zeek Install: Start Zeek on future reboots"
      shell: "/usr/local/bin/zeek enable"
      when: (node_stat.stat.exists == true)
      tags:
        - docker
        - hunt
        - linux
        - linuxdeb
        - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Create .ssh directory."
    #   ansible.builtin.file:
    #     path: "{{ lookup('env', 'HOME') }}/.ssh"
    #     state: directory
    #     owner: "{{ lookup('env', 'USER') }}"
    #     mode: 0700
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Transfer dataimport private key to .ssh"
    #   copy:
    #     src: "{{ lookup('env', 'PWD') }}/id_rsa_dataimport"
    #     dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    #     owner: "{{ lookup('env', 'USER') }}"
    #     mode: 0600
    #     backup: true
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Transfer dataimport public key to .ssh"
    #   copy:
    #     src: "{{ lookup('env', 'PWD') }}/id_rsa_dataimport.pub"
    #     dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    #     owner: "{{ lookup('env', 'USER') }}"
    #     mode: 0644
    #     backup: true
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm

    # TODO: Fix and add this back in after RITA#65 is done
    # - name: "Zeek Install: Update known_hosts with entries from known_hosts on this system"
    #   ansible.builtin.blockinfile:
    #     block: "{{ lookup('ansible.builtin.file', '{{ local_known_hosts }}') }}"
    #     path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK APPENDED DURING ZEEK INSTALL"
    #     owner: "{{ lookup('env', 'USER') }}"
    #     backup: true
    #     create: true
    #     mode: 0644
    #   when: ansible_connection != "local"
    #   tags:
    #     - docker
    #     - zeek
    #     - linux
    #     - linuxdeb
    #     - linuxrpm
